import ResponsibilityTopology.Syntax
import ResponsibilityTopology.Satisfaction
import ResponsibilityTopology.Conservativity
import ResponsibilityTopology.ExecutableSatisfaction
import ResponsibilityTopology.Audit
