import ResponsibilityTopology.Conservativity
import ResponsibilityTopology.ExecutableSatisfaction
import ResponsibilityTopology.Replay
import ResponsibilityTopology.KernelFloor

/-!
Proof-audit surface for the current mechanization milestones.
CI prints the axiom dependencies of the machine-checked declarations.
-/

#print axioms ResponsibilityTopology.derives_transport
#print axioms ResponsibilityTopology.branchConservativity
#print axioms ResponsibilityTopology.firstSat_sound
#print axioms ResponsibilityTopology.firstSat_none_rejects
#print axioms ResponsibilityTopology.firstSat_none_of_rejects
#print axioms ResponsibilityTopology.firstSat_noNewWitness
#print axioms ResponsibilityTopology.noNewWitness
#print axioms ResponsibilityTopology.satisfySound
#print axioms ResponsibilityTopology.mem_append_left_rt
#print axioms ResponsibilityTopology.mem_append_right_rt
#print axioms ResponsibilityTopology.mem_append_cases_rt
#print axioms ResponsibilityTopology.filter_sublist_rt
#print axioms ResponsibilityTopology.mem_filter_of_mem_of_true_rt
#print axioms ResponsibilityTopology.firstSat_mem
#print axioms ResponsibilityTopology.candidateSubset_of_sublist
#print axioms ResponsibilityTopology.firstSat_replay
#print axioms ResponsibilityTopology.satisfy_support_subset
#print axioms ResponsibilityTopology.supportPreservingReplay
#print axioms ResponsibilityTopology.warrantEq_refl
#print axioms ResponsibilityTopology.warrantEq_true_eq
#print axioms ResponsibilityTopology.supportHas_of_mem
#print axioms ResponsibilityTopology.supportHas_mem
#print axioms ResponsibilityTopology.supportHas_exact
#print axioms ResponsibilityTopology.projectSupport_sublist
#print axioms ResponsibilityTopology.projectSupport_keeps_support
#print axioms ResponsibilityTopology.supportProjection
#print axioms ResponsibilityTopology.lookupMap_eq_on
#print axioms ResponsibilityTopology.floorView_eq
#print axioms ResponsibilityTopology.kernelFloorLocality
#print axioms ResponsibilityTopology.normative_disabled
#print axioms ResponsibilityTopology.action_without_authorization_unsafe
#print axioms ResponsibilityTopology.share_without_selection_moveFloor
#print axioms ResponsibilityTopology.revisionFloor_insufficient_depth
#print axioms ResponsibilityTopology.accept_has_no_extra_moveFloor
#print axioms ResponsibilityTopology.review_has_no_extra_moveFloor
