import ResponsibilityTopology.Conservativity
import ResponsibilityTopology.ExecutableSatisfaction
import ResponsibilityTopology.Replay
import ResponsibilityTopology.KernelFloor
import ResponsibilityTopology.Entitlement
import ResponsibilityTopology.CanonicalRead
import ResponsibilityTopology.PythonConformance
import ResponsibilityTopology.ContextCurrentness

/-!
Proof-audit surface for the current mechanization milestones.
CI prints the axiom dependencies of the machine-checked declarations.
-/

#print axioms ResponsibilityTopology.derives_transport
#print axioms ResponsibilityTopology.branchConservativity
#print axioms ResponsibilityTopology.firstSat_sound
#print axioms ResponsibilityTopology.firstSat_none_rejects
#print axioms ResponsibilityTopology.firstSat_none_of_rejects
#print axioms ResponsibilityTopology.firstSat_noNewWitness
#print axioms ResponsibilityTopology.noNewWitness
#print axioms ResponsibilityTopology.satisfySound
#print axioms ResponsibilityTopology.mem_append_left_rt
#print axioms ResponsibilityTopology.mem_append_right_rt
#print axioms ResponsibilityTopology.mem_append_cases_rt
#print axioms ResponsibilityTopology.filter_sublist_rt
#print axioms ResponsibilityTopology.mem_filter_of_mem_of_true_rt
#print axioms ResponsibilityTopology.firstSat_mem
#print axioms ResponsibilityTopology.candidateSubset_of_sublist
#print axioms ResponsibilityTopology.firstSat_replay
#print axioms ResponsibilityTopology.satisfy_support_subset
#print axioms ResponsibilityTopology.supportPreservingReplay
#print axioms ResponsibilityTopology.warrantEq_refl
#print axioms ResponsibilityTopology.warrantEq_true_eq
#print axioms ResponsibilityTopology.supportHas_of_mem
#print axioms ResponsibilityTopology.supportHas_mem
#print axioms ResponsibilityTopology.supportHas_exact
#print axioms ResponsibilityTopology.projectSupport_sublist
#print axioms ResponsibilityTopology.projectSupport_keeps_support
#print axioms ResponsibilityTopology.supportProjection
#print axioms ResponsibilityTopology.lookupMap_eq_on
#print axioms ResponsibilityTopology.floorView_eq
#print axioms ResponsibilityTopology.kernelFloorLocality
#print axioms ResponsibilityTopology.normative_disabled
#print axioms ResponsibilityTopology.action_without_authorization_unsafe
#print axioms ResponsibilityTopology.share_without_selection_moveFloor
#print axioms ResponsibilityTopology.revisionFloor_insufficient_depth
#print axioms ResponsibilityTopology.accept_has_no_extra_moveFloor
#print axioms ResponsibilityTopology.review_has_no_extra_moveFloor
#print axioms ResponsibilityTopology.relativeBranchConservativity
#print axioms ResponsibilityTopology.entitled_of_satisfy
#print axioms ResponsibilityTopology.entitlementSupportReplay
#print axioms ResponsibilityTopology.entitled_from_projected_support
#print axioms ResponsibilityTopology.canonicalAtomTest_true_iff
#print axioms ResponsibilityTopology.toAmbient_scope_iff
#print axioms ResponsibilityTopology.toFloorEnv_lookup_canonical
#print axioms ResponsibilityTopology.derives_support_canonical
#print axioms ResponsibilityTopology.derives_support_wellFormed
#print axioms ResponsibilityTopology.satisfy_support_wellFormed
#print axioms ResponsibilityTopology.floorEqOn_fallback_irrelevant
#print axioms ResponsibilityTopology.floorView_fallback_irrelevant
#print axioms ResponsibilityTopology.derives_projection_coherent
#print axioms ResponsibilityTopology.projectedEntitled_fallback_irrelevant
#print axioms ResponsibilityTopology.projectedAmbientAdmissible_true_iff
#print axioms ResponsibilityTopology.grounded_contractiveness
#print axioms ResponsibilityTopology.grounded_fixedPoint_soundness
#print axioms ResponsibilityTopology.grounded_refresh_idempotence
#print axioms ResponsibilityTopology.grounded_invalidation_monotonicity
#print axioms ResponsibilityTopology.grounded_has_bootstrap_chain
#print axioms ResponsibilityTopology.groundedAmbient_contextActive_iff
