import ResponsibilityTopology.Conservativity
import ResponsibilityTopology.ExecutableSatisfaction
import ResponsibilityTopology.Replay

/-!
Proof-audit surface for the current mechanization milestones.
CI prints the axiom dependencies of the machine-checked declarations.
-/

#print axioms ResponsibilityTopology.derives_transport
#print axioms ResponsibilityTopology.branchConservativity
#print axioms ResponsibilityTopology.firstSat_sound
#print axioms ResponsibilityTopology.firstSat_none_rejects
#print axioms ResponsibilityTopology.firstSat_none_of_rejects
#print axioms ResponsibilityTopology.firstSat_noNewWitness
#print axioms ResponsibilityTopology.noNewWitness
#print axioms ResponsibilityTopology.satisfySound
#print axioms ResponsibilityTopology.firstSat_mem
#print axioms ResponsibilityTopology.candidateSubset_of_sublist
#print axioms ResponsibilityTopology.firstSat_replay
#print axioms ResponsibilityTopology.satisfy_support_subset
#print axioms ResponsibilityTopology.supportPreservingReplay
#print axioms ResponsibilityTopology.projectSupport_sublist
#print axioms ResponsibilityTopology.projectSupport_keeps_support
#print axioms ResponsibilityTopology.supportProjection
