import ResponsibilityTopology.RepairSufficiency

/-!
Proof-audit surface for the Paper 3 revision/revalidation line.
This file is intentionally separate from the frozen Paper 1/2 audit surface.
-/

#print axioms ResponsibilityTopology.refreshActiveContexts_active_iff
#print axioms ResponsibilityTopology.refreshActiveContexts_contracts
#print axioms ResponsibilityTopology.grounded_adopt_requires_baseCurrent
#print axioms ResponsibilityTopology.grounded_adopt_issuer_grounded
#print axioms ResponsibilityTopology.challengeInvalidate_usable_implies_pre
#print axioms ResponsibilityTopology.challengeStep_baseCurrent_stricter
#print axioms ResponsibilityTopology.challengeStep_baseCurrentRead_stricter
#print axioms ResponsibilityTopology.challengeStep_activationRead_eq_withBaseCurrent
#print axioms ResponsibilityTopology.challengeStep_grounded_post_implies_pre
#print axioms ResponsibilityTopology.refresh_staleActivation_notActive
#print axioms ResponsibilityTopology.refresh_activeAdopt_implies_issuerActive
#print axioms ResponsibilityTopology.refresh_issuerLoss_cascades
#print axioms ResponsibilityTopology.challengeReachable_to_refreshReachable
#print axioms ResponsibilityTopology.refreshStep_exact
#print axioms ResponsibilityTopology.challengeRefresh_retained_implies_preGrounded
#print axioms ResponsibilityTopology.staleDependency_warrant_iff
#print axioms ResponsibilityTopology.staleDependency_license_iff
#print axioms ResponsibilityTopology.staleDependency_context_iff
#print axioms ResponsibilityTopology.repairSet_hits_edge
#print axioms ResponsibilityTopology.repairSet_monotone
#print axioms ResponsibilityTopology.repairProblem_edge_is_stale
#print axioms ResponsibilityTopology.repairProblem_stale_has_edge
#print axioms ResponsibilityTopology.minimalRepairSet_is_repairSet
#print axioms ResponsibilityTopology.historicalWellFormedness_separate_from_staleness
#print axioms ResponsibilityTopology.refreshActiveContexts_activationRead_eq_refreshed
#print axioms ResponsibilityTopology.repairObligation_refresh_iff
#print axioms ResponsibilityTopology.repairSet_realization_restores_edges
#print axioms ResponsibilityTopology.repairSet_realization_restores_staleDependencies
#print axioms ResponsibilityTopology.repairSet_sufficient_before_refresh
#print axioms ResponsibilityTopology.repairSet_sufficient_after_refresh
#print axioms ResponsibilityTopology.minimalRepairSet_sufficient_after_refresh
